### ISSUE TITLE
Can't hit REST API

### ISSUE THREAD

**Issue by jrgp** [zeit/cosmosdb-server#19]
Hi,

I'm able to properly start the app (after installing with npm -g):

```
$ cosmosdb-server -p 3000
Ready to accept connections at [::]:3000
```

But I can't hit it:

```
$ curl localhost:3000
curl: (52) Empty reply from server
```

I'm on node v12.13.0 on RHEL7.

Do you know how I can proceed with this?

**Comment by nkzawa** [comment]
It's because the server only supports https protocol, so need to append `https://`.

```sh
 $ curl https://localhost:3000 --insecure
```

Also add the the `--insecure` (`-k`) option to bypass cert verification since the server uses a self signed cert.

**Comment by jrgp** [comment]
Thanks!
