### ISSUE TITLE
How can i run it?

### ISSUE THREAD

**Issue by renato04** [zeit/cosmosdb-server#3]
Hello!

I run `npm install`.
And now I'm trying to use `cosmosdb-server -p 3000` but is giving `command not found error` 

Am I doing something wrong?

Thanks!

**Comment by christopheranderson** [comment]
If you ran:

`npm i @zeit/cosmosdb-server`

that will put the cosmosdb-server command in your `./node_modules/.bin`. Then you can run:

`npx cosmosdb-server -p 3000`

**Comment by renato04** [comment]
Thanks for answering me 

After i run `npm i` command
I'm getting the following error

```
root@55c2ef61899e:/cosmosdb-server# npm i @zeit/cosmosdb-server
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@zeit/cosmosdb-server" under a package
npm ERR! also called "@zeit/cosmosdb-server". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T17_17_46_957Z-debug.log
```

**Comment by TooTallNate** [comment]
Do it from a different directory (no need to clone this repo), or install it globally with `npm i -g @zeit/cosmosdb-server` and then the `cosmosdb-server` command will be available.

**Comment by christopheranderson** [comment]
It looks like you cloned the repo and are trying to run it from the clone. What @TooTallNate said is right. That is the easiest way and likely what you'd do for any project you'd be trying to use it from for local testing/CI purposes. Ignore the rest of this if that's what you want to do.

If you want to run it from the cloned repo for contributing purposes, you need to:
```
npm i
npm run build
node ./lib/cli -p 3000
```

(`node ./lib/cli` is what is in the `bin` property in the package.json)

**Comment by renato04** [comment]
Thanks! It worked following @TooTallNate tips.
@christopheranderson it was just for testing.
