### ISSUE TITLE
Is there a way to query or get the document recorded?

### ISSUE THREAD

**Issue by renato04** [zeit/cosmosdb-server#4]
Hi!

After I run the test I want to see the document created.
Is there a way to do that?

I'm accessing `https://localhost:3000` and I'm getting `{}` as a response.

**Comment by nkzawa** [comment]
You can do it just like you do always.

This server is empty when it booted, so you need to create databases, containers, and items at first.
Ensure to not verify SSL certificate, since it uses self-signed one.

**Comment by renato04** [comment]
@nkzawa Thank you!
